# This file was generated by GoReleaser. DO NOT EDIT.
cask "pastevault" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "239a941b34afa7c532822b82c3bb9a2175977fea443c6f32d530f80873a8926a"
      url "https://github.com/arc53/pastevault/releases/download/v#{version}/pastevault_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "002478f7f7c773fd7437ed923103e5a568f4aaddcb80ee82d2f08d2cf3677331"
      url "https://github.com/arc53/pastevault/releases/download/v#{version}/pastevault_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2c8cb7beaab8e17b275b4eafa1414560afc4b6b4b83a0c0d17c5a60be808f2e2"
      url "https://github.com/arc53/pastevault/releases/download/v#{version}/pastevault_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "85119c897f208eca025a86b4b58a987c7fd82d20474249f4ad7dde452ac74660"
      url "https://github.com/arc53/pastevault/releases/download/v#{version}/pastevault_linux_arm64.tar.gz"
    end
  end

  name "pastevault"
  desc "End-to-end encrypted file sharing from the terminal"
  homepage "https://pastevault.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pastevault"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pastevault"]
    end
  end

  # No zap stanza required

end
